// <auto-generated />
using System;
using ERP.Accounting.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERP.Accounting.Infrastructure.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260428224003_Company")]
    partial class Company
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERP.Accounting.Domain.Entities.Configuration.CompanyEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(40)");

                    b.Property<byte[]>("logo")
                        .HasColumnType("bytea");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<Guid>("uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("id");

                    b.HasIndex("uuid")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
